### ISSUE TITLE
写在人生的一个小小节点 |

### ISSUE THREAD

**Issue by lsdsjy** [lsdsjy/lsdsjy.github.io#1]
https://lsdsjy.github.io/node/ 

 大约是四年前，我写了一篇文章，叫做《大学的十六分之一》。当时的我第一次离开家乡那座小城，独自来到北京读书；高中时对大学的憧憬和计划一点点地变得模糊，日常生活被懒惰和消极侵占，但又仍然保持一点清醒，所以才能写下那些文字。可惜的是后来再也没有类似的场景。前些日子从学校毕业的时候，看到别人的大学四年总结，我却想不到能写些什么。我不是一个好学生，也没做些有趣的事，甚至没能成为一个合格的人。

**Comment by euukey** [comment]
针不戳

**Comment by lsdsjy** [comment]
testt
